name: Generate Lilypond music sheets
on:
  push:
jobs:
  build_sheets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Generate PDF music sheets
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./boismortier/pb278
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: Releases
        path: '**/*.pdf'

