name: Generate Lilypond music sheets
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Generate PDF music sheets for PB278
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./boismortier/pb278
    - name: Generate PDF music sheets for PB223
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./boismortier/pb223
    - name: Generate PDF music sheets for IEC8
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./chedeville/iec8
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: '**/*.pdf'
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: download release artefact
      uses: actions/download-artifact@master
      with:
        name: dist
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          **/*.pdf
