name: Generate Lilypond music sheets
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Generate PDF music sheets
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./boismortier/pb278
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: '**/*.pdf'
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: download release artefact
      uses: actions/download-artifact@master
      with:
        name: dist

    - name: Debug
      run: |
        find . -iname "*.pdf"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.pdf

