name: Generate Lilypond sheet music
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Build PDFs for 6 a deux
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./boismortier/6a2
    - name: Build PDFs for IEC8
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./chedeville/iec8
    - name: Build PDFs for Chedeville op 7
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./chedeville/op7
#    - name: Build PDFs for Hotteterre
#      uses: holgerpeters/lilypond-github-action@main
#      with:
#        path: ./hotteterre/musette
    - name: Build PDFs for christmas songs
      uses: holgerpeters/lilypond-github-action@main
      with:
        path: ./weihnacht
    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: '**/*.pdf'
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/main')
    steps:
    - name: download release artefact
      uses: actions/download-artifact@master
      with:
        name: dist
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        draft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        tag_name: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref || 'refs/tags/latest' }}
        files: |
          **/*.pdf
