name: Generate Lilypond music sheets
on:
  push:
jobs:
  build_sheets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Generate PDF music sheets
      uses: holgerpeters/lilypond-github-action@main
      with:
        args: boismortier/pb278
#      - name: Push Local Changes
#        run: |
#          git config --local user.email "${{ secrets.GIT_USERNAME }}"
#          git config --local user.name "${{ secrets.GIT_EMAIL }}"
#          mkdir -p ${{github.workspace}}/docs/
#          mv -f *.midi ${{github.workspace}}/docs/
#          mv -f *.pdf ${{github.workspace}}/docs/
#          mv -f *.png ${{github.workspace}}/docs/
#          git add ${{github.workspace}}/docs/
#          git commit -m "Add changes" -a
#      - name: Push changes
#        uses: ad-m/github-push-action@main
#        with:
#          branch: gh-pages
#          github_token: ${{ secrets.GITHUB_TOKEN }}
